---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: La fábrica de cargas de trabajo de BlueXP  para creadores es una herramienta de creación de entornos de creación rápida para creadores de software. 
---
= Obtenga información sobre la fábrica de cargas de trabajo de BlueXP  para creadores
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La fábrica de cargas de trabajo de BlueXP  para creadores es una herramienta de creación de entornos de creación rápida para creadores de software. Permite una rápida configuración de entornos de desarrollo personales, lo que ahorra tiempo y permite el autoservicio para los desarrolladores a la vez que permite a los equipos de DevOps mantener el control de la infraestructura. Con Builders, los desarrolladores de software pueden crear espacios de trabajo rápidamente sin necesidad de almacenamiento de datos especializado ni comprensión de la infraestructura de desarrollo.



== ¿Qué es la fábrica de cargas de trabajo BlueXP  para constructores?

La fábrica de cargas de trabajo de BlueXP  para creadores está diseñada para agilizar la forma en que los desarrolladores gestionan e interactúan con las diferentes versiones de su software. Builders se integra sin problemas con Perforce Helix Core para proporcionar clones instantáneos de versiones de software y crear espacios de trabajo listos para usar para el desarrollo, control de calidad y procesos CI/CD.

Con Builders, puede crear fácilmente un proyecto y asignar un volumen que represente su entorno de software y sus artefactos. A medida que actualiza su software, puede tomar instantáneas del volumen, capturando el estado de su software en ese momento. Esto significa que puede acceder a cualquier versión de su software al instante sin la necesidad de volver a sincronizar con el sistema de control de versiones, ahorrando tiempo y recursos valiosos.

Al aprovechar las capacidades de copias Snapshot y clonación de ONTAP, Builders mejora su flujo de trabajo de desarrollo, lo que le permite acceder rápidamente a varias versiones de su software, acelerar los ciclos de desarrollo y ayudar a reducir los plazos de comercialización.

Para obtener más información sobre la fábrica de cargas de trabajo, consulte la link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["información general de la fábrica de cargas de trabajo"^].



== Fábrica de cargas de trabajo de BlueXP  para las características de los creadores

La fábrica de cargas de trabajo de BlueXP  para creadores ofrece las siguientes características:

* Crear, editar y eliminar proyectos
* Crear snapshots de versiones de software definidas
* Crear y eliminar espacios de trabajo (basados en clones)
* Cree políticas de acceso para controlar el acceso a un proyecto
* Analice el uso de la capacidad de cada proyecto
* Controlar los límites de tamaño de los clones y la retención de clones para cada proyecto
* Integración con sistemas de control de versiones como Perforce




== Proyectos y espacios de trabajo en Builders

Cuando utiliza Builders, crea un proyecto y asigna un volumen que representa el entorno de software y sus artefactos. Cada vez que cree una nueva versión del software, debe volver a sincronizar los datos del volumen y crear una instantánea del proyecto para marcar el estado del volumen como una versión conocida. El volumen de origen del proyecto puede obtener actualizaciones sucesivas y tener varias instantáneas para marcar varias versiones. Puede utilizar cada copia Snapshot inmediatamente como clon instantáneo, de un repositorio editable dedicado o compartido disponible para desarrolladores, para procesos de control de calidad o de creación. Un clon en el contexto de una versión de software específica es un espacio de trabajo.



== Modos operativos en fábrica de cargas de trabajo

Tres modos operativos diferentes - _BASIC_, _READ_ y _AUTOMATIC_ - ofrecen opciones flexibles para la implementación dentro y fuera de la fábrica de cargas de trabajo. Obtenga un valor inmediato en el modo de confianza cero en _BASIC_ con fragmentos de código para su uso fuera de la fábrica de cargas de trabajo. Obtenga valor incremental con confianza incremental en los modos _READ_ y _AUTOMATIC_.

Más información sobre link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["modos operativos en fábrica de cargas de trabajo"^].



== Automatización con la fábrica de cargas de trabajo CodeBox

La fábrica de cargas de trabajo introduce la automatización incorporada con _CodeBox_. CodeBox ofrece las siguientes ventajas de automatización:

* *Generación de fragmentos de código*: Los fragmentos de infraestructura como código (IAC) se generan durante la creación de recursos, lo que permite una integración perfecta con los flujos de trabajo de orquestación existentes.
* *Copiloto de infraestructura como código*: El CodeBox es un copiloto de infraestructura como código (IAC) que ayuda a los desarrolladores y DevOps a generar código para ejecutar cualquier operación soportada por la fábrica de cargas de trabajo.
* *Visor de código y catálogo de automatización*: El CodeBox proporciona un visor de código para un análisis rápido de la automatización y un catálogo de automatización para una rápida reutilización futura.




== Coste

No hay costo para usar la capacidad de Builders de la fábrica de cargas de trabajo.



== Licencia

No se necesitan licencias especiales de NetApp para utilizar las capacidades de los creadores de la fábrica de cargas de trabajo.



=== Regiones admitidas

Builders es apoyado en todas las regiones comerciales donde FSX para ONTAP es apoyado. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Consulte las regiones de Amazon admitidas."^]

No se admiten las siguientes regiones de AWS:

* Regiones de China
* Regiones GovCloud (EE. UU.
* Cloud secreto
* Cloud secreto superior




== Obtener ayuda

Amazon FSX para ONTAP de NetApp es una solución de primera parte de AWS. Para preguntas o problemas de soporte técnico asociados con tu ONTAP sistema de archivos, infraestructura o cualquier solución que use este servicio, usa el Centro de soporte de tu consola de administración de AWS para abrir un caso de soporte con AWS. Seleccione el servicio "FSX for ONTAP" y la categoría adecuada. Proporcione la información restante necesaria para crear su caso de soporte de AWS.

Para preguntas generales sobre la fábrica de cargas de trabajo o las aplicaciones y servicios de fábrica de cargas de trabajo, consulte link:get-help-builders.html["Obtenga ayuda para Builders para la fábrica de cargas de trabajo"].
