---
settings:
  name: Builders workloads
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Desarrolladores de documentos de cargas de trabajo
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/known-limitations.html"
  - title: Manos a la obra
    entries:
    - title: Obtenga información sobre la fábrica de cargas de trabajo de BlueXP 
        para creadores
      url: "/learn-builders.html"
    - title: Inicio rápido
      url: "/quick-start-builders.html"
    - title: Requisitos
      url: "/requirements-builders.html"
    - title: Integración de creadores con Perforce
      url: "/integrate-perforce.html"
  - title: Use cargas de trabajo de creadores
    entries:
    - title: Gestionar proyectos
      url: "/manage-projects.html"
    - title: Administrar versiones del proyecto
      url: "/version-projects.html"
    - title: Cree un espacio de trabajo
      url: "/create-workspaces.html"
    - title: Automatice con CodeBox
      url: "/automate-codebox.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/support-registration.html"
    - title: Obtenga ayuda
      url: "/get-help-builders.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
