---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, builders, workload factory' 
summary: Descubra las novedades de la fábrica de cargas de trabajo para bases de datos. 
---
= Novedades de la fábrica de cargas de trabajo de BlueXP  para creadores
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades con la capacidad de Builders de la fábrica de cargas de trabajo.



== 16 de junio de 2025



=== Soporte para clones

Ahora puede clonar un proyecto en la fábrica de cargas de trabajo de BlueXP para Builders. Al clonar un proyecto, Builders crea uno nuevo a partir de una instantánea, con la misma configuración que el original. La clonación es útil para crear rápidamente proyectos similares o para realizar pruebas. Puede montar el nuevo clon del proyecto siguiendo las instrucciones de Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Administrar versiones de la fábrica de carga de trabajo de BlueXP para proyectos de Builders"]



== 4 de mayo de 2025



=== Terminología de permisos actualizada

La interfaz de usuario y la documentación de la fábrica de carga de trabajo ahora usan "solo lectura" para referirse a los permisos de lectura y "lectura/escritura" para referirse a los permisos de automatización.



== 1 de diciembre de 2024



=== Versión inicial de carga de trabajo de constructores

La fábrica de cargas de trabajo de BlueXP  para creadores simplifica el uso y el acceso a las versiones de software, lo que elimina la necesidad de herramientas o scripts personalizados. Le permite utilizar versiones de software como clones instantáneos integrados con Perforce Helix Core como espacio de trabajo práctico para sus procesos de desarrollo, ahorrando tiempo y recursos.

La versión inicial incluye la capacidad de administrar proyectos y espacios de trabajo, y automatizar acciones con CodeBox. También puede integrar Builders con Perforce Helix Core, para que pueda administrar diferentes versiones de cada proyecto y cambiar entre ellas rápidamente.
